apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: test-api
        resources:
          $patch: delete