apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: fagkveld-
resources:
- deployment.yaml
secretGenerator:
- name: test-api-secret
generatorOptions:
  disableNameSuffixHash: true
